version: "3"
services:
  frontend:
    build: ./frontend
    environment:
      TASKS_ADDRESS: 'localhost:8000'
    ports:
      - "80:80"
    depends_on:
      - tasks
  auth:
    image: shykhovmyron/auth-kub:latest
  users:
    image: shykhovmyron/users-kub:latest
    environment:
      AUTH_ADDRESS: 'auth'
    ports:
      - "8080:8080"
  tasks:
    image: shykhovmyron/tasks-kub:latest
    ports:
      - "8000:8000"
    environment:
      AUTH_ADDRESS: 'auth'
      TASKS_FOLDER: tasks

