apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: tasks
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-api
          image: shykhovmyron/tasks-kub:latest
          env:
            - name: AUTH_ADDRESS
              value: $(AUTH_INSIDE_SERVICE_SERVICE_HOST)
            - name: TASKS_FOLDER
              value: tasks
#          volumeMounts:
#            - mountPath: /app/tasks
#              name: tasks-volume
#      volumes:
#        - name: tasks-volume
#          hostPath:
#            path: /tasks
#            type: DirectoryOrCreate
  selector:
    matchLabels:
      app: tasks

---

apiVersion: v1
kind: Service
metadata:
  name: tasks-outside-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
