apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: shykhovmyron/users-kub:latest
          env:
            - name: AUTH_ADDRESS
              value: $(AUTH_INSIDE_SERVICE_SERVICE_HOST)
  selector:
    matchLabels:
      app: users

---

apiVersion: v1
kind: Service
metadata:
  name: users-outside-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080