apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: shykhovmyron/users-api-kub:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth-api
          image: shykhovmyron/auth-api-kub:latest
  selector:
    matchLabels:
      app: users
